### PR TITLE
fix: fetch data in the order it was stored

### LINKED ISSUE #54: the cities that get reloaded on refresh load in the wrong order
because when the app gets reloaded, it will call the api for each and every city. Because it does this asynchronously, it will load the cities in a random order. After the loading bar gets implemented, try to order the cities more appropriately.

### PR DESCRIPTION
**Pull request by shauntober**
Hey again!

## Changes
- general cleanup (favouring const over let where appropriate, removing redundant code etc)
- now correctly appends rather than prepends semicolon when saving item to localstorage (this was causing a malformed request to be fired off on page load due to the way the string is being parsed)
- switched to async/await for fetching weather data on page load so that the original order is retained on subsequent visits (fixes #54)

### CODE REVIEW

File: src/components/InputFields.svelte [hunk 1]
```diff
@@ -9,10 +9,11 @@
   function handleClick() {
     getWeather(newCityName, newCountryName)
       .then((weather) => {
-        let newCity = new City(newCityName, newCountryName, weather.data);
+        const newCity = new City(newCityName, newCountryName, weather.data);
+        const savedCities = localStorage.getItem("cities");
         localStorage.setItem(
           "cities",
-          localStorage.getItem("cities") + `;${newCityName},${newCountryName}`
+          `${savedCities && `${savedCities};`}${newCityName},${newCountryName}`
```
Comment (bartius-nigel) [inline src/components/InputFields.svelte:16]: i dont know how this works lol but it is a lot better than accessing the local storage again.

**Review by bartius-nigel — APPROVED** [review]
